### ISSUE TITLE
Mono input support

### ISSUE THREAD

**Issue by dmnc** [vacaboja/tg#4]
Currently, when using a mono input (I'm using a piezoelectric mic) tg gives the following error.

```
Error opening audio input: Invalid number of channels
```

I have tried reducing the number of channels at https://github.com/vacaboja/tg/blob/master/audio.c#L54 by doing

```
    PaDeviceIndex defaultIndex = Pa_GetDefaultInputDevice();
    int maxChannels = Pa_GetDeviceInfo(defaultIndex)->maxInputChannels;
    err = Pa_OpenDefaultStream(&stream,maxChannels,0,paFloat32,PA_SAMPLE_RATE,paFramesPerBufferUnspecified,paudio_callback,x);
```

Or even just forcing to 1, but this kills the signal entirely.

I'm not a C programmer at all, so I'm just fumbling around in the dark here really :disappointed:

**Comment by vacaboja** [comment]
Thanks,

I made a branch called "test" to try and resolve your issue. It's a crude solution, but I just want to see if it works. May I ask you to try it and tell me the result?

**Comment by dmnc** [comment]
Success!

The test branch works on both a stereo and mono input. Perfect.
