### ISSUE TITLE
Supporting SemVer

### ISSUE THREAD

**Issue by dmnc** [vacaboja/tg#7]
It would be really nice to support http://semver.org/.

It's picking up lots of support and provides a really easy to understand framework for picking version numbers.

Please ignore and close if you're already intending to do this. I just saw a 0.4.99 version number somewhere and thought it was worth highlighting.

**Comment by vacaboja** [comment]
Hi thanks,

I am aware of semantic versioning. Actually, 0.4.99 was meant to be just a placeholder to say: "if there are no issues on the macintosh I will announce this as 0.5.0". Do you agree with me that 0.5.0 should be the right version number?

**Comment by dmnc** [comment]
I do. All looks good to me.
