### ISSUE TITLE
Interface is missing icons on Mac OS X

### ISSUE THREAD

**Issue by dmnc** [vacaboja/tg#8]
I see this on the snapshot tab

![image](https://user-images.githubusercontent.com/144790/27059298-a87af8d8-4fcd-11e7-8604-2b4479076bba.png)

And this in the log:

```
(tg:42716): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

Icons seem to be missing across the interface. The open and close file dialogue suffers from the same fate.

I am unsure if this is a tg thing or a GTK+ thing?

**Comment by dmnc** [comment]
Scrub that. All icons are missing from the interface. Is this a GTK thing or a tg thing?

**Comment by dmnc** [comment]
Looks like I need to install the adwaita-icon-theme

**Comment by vacaboja** [comment]
Hi,

it seems to me that, if you have to install the icon theme by hand, there must be a bug in the homebrew packaging. For instance I do not reference explicitly neither Adwaita not check-symbolic.svg in my code: these are all defaults defined internally in GTK+3. So probably the gtk+3 package should have a dependency on adwaita-icon-theme.

Maybe you could submit a bug report to the homebrew maintainers...
